[package]
name = "rust_update_comic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3"
chrono = "0.4"
clap = "4.4.11"
indicatif = "0.17.0"